include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: false
    avoid_print: false
    prefer_single_quotes: true
    prefer_interpolation_to_compose_strings: false
analyzer:
  enable-experiment:
    - records
    - patterns
    - sealed-class