include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: false
    avoid_print: false
    prefer_single_quotes: true
    prefer_interpolation_to_compose_strings: false
    prefer_is_empty: false
    avoid_function_literals_in_foreach_calls: false
    prefer_final_locals: true
analyzer:
  exclude:
    - lib/src/rust/frb_generated.dart
  enable-experiment:
    - records
    - patterns
    - sealed-class
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true