#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.68.0.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

use crate::common::Ad;
use crate::common::Author;
use crate::common::BookMetaDataFromProvider;
use crate::common::LbcCredential;

// Section: wire functions

fn wire_detect_barcode_in_image_impl(
    port_: MessagePort,
    img_path: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "detect_barcode_in_image",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_img_path = img_path.wire2api();
            move |task_callback| detect_barcode_in_image(api_img_path)
        },
    )
}
fn wire_get_metadata_from_isbns_impl(
    port_: MessagePort,
    isbns: impl Wire2Api<Vec<String>> + UnwindSafe,
    path: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_metadata_from_isbns",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_isbns = isbns.wire2api();
            let api_path = path.wire2api();
            move |task_callback| get_metadata_from_isbns(api_isbns, api_path)
        },
    )
}
fn wire_get_auto_metadata_from_bundle_impl(
    port_: MessagePort,
    path: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_auto_metadata_from_bundle",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_path = path.wire2api();
            move |task_callback| get_auto_metadata_from_bundle(api_path)
        },
    )
}
fn wire_get_metadata_from_provider_impl(
    port_: MessagePort,
    provider: impl Wire2Api<ProviderEnum> + UnwindSafe,
    isbn: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_metadata_from_provider",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_provider = provider.wire2api();
            let api_isbn = isbn.wire2api();
            move |task_callback| Ok(get_metadata_from_provider(api_provider, api_isbn))
        },
    )
}
fn wire_publish_ad_impl(
    port_: MessagePort,
    ad: impl Wire2Api<Ad> + UnwindSafe,
    credential: impl Wire2Api<LbcCredential> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "publish_ad",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_ad = ad.wire2api();
            let api_credential = credential.wire2api();
            move |task_callback| Ok(publish_ad(api_ad, api_credential))
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<i32> for i32 {
    fn wire2api(self) -> i32 {
        self
    }
}

impl Wire2Api<ProviderEnum> for i32 {
    fn wire2api(self) -> ProviderEnum {
        match self {
            0 => ProviderEnum::Babelio,
            1 => ProviderEnum::GoogleBooks,
            2 => ProviderEnum::BooksPrice,
            3 => ProviderEnum::AbeBooks,
            4 => ProviderEnum::LesLibraires,
            _ => unreachable!("Invalid variant for ProviderEnum: {}", self),
        }
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for Author {
    fn into_dart(self) -> support::DartAbi {
        vec![self.first_name.into_dart(), self.last_name.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Author {}

impl support::IntoDart for BarcodeDetectResult {
    fn into_dart(self) -> support::DartAbi {
        vec![self.value.into_dart(), self.corners.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BarcodeDetectResult {}

impl support::IntoDart for BarcodeDetectResults {
    fn into_dart(self) -> support::DartAbi {
        vec![self.results.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BarcodeDetectResults {}

impl support::IntoDart for BookMetaDataFromProvider {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.title.into_dart(),
            self.authors.into_dart(),
            self.blurb.into_dart(),
            self.keywords.into_dart(),
            self.market_price.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BookMetaDataFromProvider {}

impl support::IntoDart for ISBNMetadataPair {
    fn into_dart(self) -> support::DartAbi {
        vec![self.isbn.into_dart(), self.metadatas.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for ISBNMetadataPair {}

impl support::IntoDart for Point {
    fn into_dart(self) -> support::DartAbi {
        vec![self.x.into_dart(), self.y.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Point {}

impl support::IntoDart for ProviderEnum {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::Babelio => 0,
            Self::GoogleBooks => 1,
            Self::BooksPrice => 2,
            Self::AbeBooks => 3,
            Self::LesLibraires => 4,
        }
        .into_dart()
    }
}
impl support::IntoDart for ProviderMetadataPair {
    fn into_dart(self) -> support::DartAbi {
        vec![self.provider.into_dart(), self.metadata.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for ProviderMetadataPair {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
